<a href="https://colab.research.google.com/github/zmuhls/jeopardy-lm/blob/main/jeopardy_finetune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jeopardy LM: TinyLlama Fine-tuning with LoRA
# Google Colab Implementation

This notebook demonstrates how to:
1. Download Jeopardy questions from a public dataset
2. Fine-tune TinyLlama-1.1B using PEFT/LoRA
3. Create a simple API server to serve the model
4. Evaluate the model's performance on Jeopardy questions

This implementation is designed for Google Colab with GPU acceleration.

In [37]:
# @title Mount Google Drive (Optional)
# @markdown Run this to save/load data and models from Google Drive

from google.colab import drive
use_drive = False  # Set to True to use Google Drive for storage

if use_drive:
    drive.mount('/content/drive')
    output_dir = "/content/drive/MyDrive/jeopardy-lm"
else:
    # Create directory for output in Colab local storage
    output_dir = "/content/jeopardy-lm"

from google.colab import userdata
userdata.get('WANDB_API_KEY')

import os
os.makedirs(output_dir, exist_ok=True)
print(f"Model and data will be saved to: {output_dir}")

Model and data will be saved to: /content/jeopardy-lm

In [ ]:
# @title Install required packages
# @markdown Run this cell to install all necessary dependencies

!pip install torch==2.0.1 transformers==4.30.2 peft==0.4.0 bitsandbytes==0.40.2 accelerate==0.20.3
!pip install datasets==2.13.1 tqdm pandas flask ipywidgets matplotlib tensorboard

# Check for GPU availability
import torch
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU device: {torch.cuda.get_device_name(0)}")
    print(f"GPU memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
else:
    print("WARNING: No GPU detected. Training will be slow.")
    print("Go to Runtime > Change runtime type > Hardware accelerator > GPU to enable GPU.")

In [38]:
# @title Convert Jeopardy Dataset to JSONL Format
# @markdown This cell converts the downloaded Jeopardy dataset to JSONL format for fine-tuning

import pandas as pd
import json
import os
from sklearn.model_selection import train_test_split

# Path for input CSV and output JSONL
jeopardy_csv_path = os.path.join(output_dir, "jeopardy_data.csv")
data_dir = os.path.join(output_dir, "data")
train_path = os.path.join(data_dir, "jeopardy_train.jsonl")
val_path = os.path.join(data_dir, "jeopardy_val.jsonl")

print(f"Reading Jeopardy data from {jeopardy_csv_path}")

try:
    # Read the CSV file
    df = pd.read_csv(jeopardy_csv_path)
    print(f"Loaded {len(df)} questions")

    # Ensure required columns exist
    required_cols = ['category', 'question', 'answer']
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"Required column '{col}' not found in dataset. Available columns: {list(df.columns)}")

    # Filter out any rows with missing values in key columns
    df = df.dropna(subset=required_cols)
    print(f"After dropping rows with missing values: {len(df)} questions")

    # Format the data for fine-tuning
    formatted_data = []
    for _, row in df.iterrows():
        # Format prompt and completion
        prompt = f"Category: {row['category']}\nClue: {row['question']}\nAnswer in the form of a question:"

        # Ensure the answer is in the form of a question
        answer = row['answer']
        if not answer.lower().startswith('what') and not answer.lower().startswith('who'):
            completion = f"What is {answer}?"
        else:
            completion = answer

        formatted_data.append({
            "prompt": prompt,
            "completion": completion
        })

    print(f"Formatted {len(formatted_data)} questions")

    # Split into train and validation sets (90/10 split)
    train_data, val_data = train_test_split(formatted_data, test_size=0.1, random_state=42)
    print(f"Split into {len(train_data)} training examples and {len(val_data)} validation examples")

    # Write to JSONL files
    with open(train_path, 'w') as f:
        for item in train_data:
            f.write(json.dumps(item) + '\n')

    with open(val_path, 'w') as f:
        for item in val_data:
            f.write(json.dumps(item) + '\n')

    print(f"Successfully wrote training data to {train_path}")
    print(f"Successfully wrote validation data to {val_path}")

    # Preview
    print("\nSample training example:")
    print(f"Prompt: {train_data[0]['prompt']}")
    print(f"Completion: {train_data[0]['completion']}")

except Exception as e:
    print(f"Error converting dataset: {e}")
    raise Exception("Failed to convert Jeopardy dataset to JSONL format.")

Reading Jeopardy data from /content/jeopardy-lm/jeopardy_data.csv
Loaded 40 questions
After dropping rows with missing values: 40 questions
Formatted 40 questions
Split into 36 training examples and 4 validation examples
Successfully wrote training data to /content/jeopardy-lm/data/jeopardy_train.jsonl
Successfully wrote validation data to /content/jeopardy-lm/data/jeopardy_val.jsonl

Sample training example:
Prompt: Category: MATHEMATICS
Clue: Value of Pi to 2 decimal places
Answer in the form of a question:
Completion: What is 3.14?

In [39]:
# @title Convert Jeopardy Dataset to JSONL Format
# @markdown This cell converts the downloaded Jeopardy dataset to JSONL format for fine-tuning

import pandas as pd
import json
import os
from sklearn.model_selection import train_test_split

# Path for input CSV and output JSONL
jeopardy_csv_path = os.path.join(output_dir, "jeopardy_data.csv")
data_dir = os.path.join(output_dir, "data")
train_path = os.path.join(data_dir, "jeopardy_train.jsonl")
val_path = os.path.join(data_dir, "jeopardy_val.jsonl")

# Create the 'data' directory if it doesn't exist
os.makedirs(data_dir, exist_ok=True) # This line creates the necessary directory

print(f"Reading Jeopardy data from {jeopardy_csv_path}")

try:
    # Read the CSV file
    df = pd.read_csv(jeopardy_csv_path)
    print(f"Loaded {len(df)} questions")

    # Ensure required columns exist
    required_cols = ['category', 'question', 'answer']
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"Required column '{col}' not found in dataset. Available columns: {list(df.columns)}")

    # Filter out any rows with missing values in key columns
    df = df.dropna(subset=required_cols)
    print(f"After dropping rows with missing values: {len(df)} questions")

    # Format the data for fine-tuning
    formatted_data = []
    for _, row in df.iterrows():
        # Format prompt and completion
        prompt = f"Category: {row['category']}\nClue: {row['question']}\nAnswer in the form of a question:"

        # Ensure the answer is in the form of a question
        answer = row['answer']
        if not answer.lower().startswith('what') and not answer.lower().startswith('who'):
            completion = f"What is {answer}?"
        else:
            completion = answer

        formatted_data.append({
            "prompt": prompt,
            "completion": completion
        })

    print(f"Formatted {len(formatted_data)} questions")

    # Split into train and validation sets (90/10 split)
    train_data, val_data = train_test_split(formatted_data, test_size=0.1, random_state=42)
    print(f"Split into {len(train_data)} training examples and {len(val_data)} validation examples")

    # Write to JSONL files
    with open(train_path, 'w') as f:
        for item in train_data:
            f.write(json.dumps(item) + '\n')

    with open(val_path, 'w') as f:
        for item in val_data:
            f.write(json.dumps(item) + '\n')

    print(f"Successfully wrote training data to {train_path}")
    print(f"Successfully wrote validation data to {val_path}")

    # Preview
    print("\nSample training example:")
    print(f"Prompt: {train_data[0]['prompt']}")
    print(f"Completion: {train_data[0]['completion']}")

except Exception as e:
    print(f"Error converting dataset: {e}")
    raise Exception("Failed to convert Jeopardy dataset to JSONL format.")

Reading Jeopardy data from /content/jeopardy-lm/jeopardy_data.csv
Loaded 40 questions
After dropping rows with missing values: 40 questions
Formatted 40 questions
Split into 36 training examples and 4 validation examples
Successfully wrote training data to /content/jeopardy-lm/data/jeopardy_train.jsonl
Successfully wrote validation data to /content/jeopardy-lm/data/jeopardy_val.jsonl

Sample training example:
Prompt: Category: MATHEMATICS
Clue: Value of Pi to 2 decimal places
Answer in the form of a question:
Completion: What is 3.14?

In [40]:
# @title Load Dataset for Fine-tuning
# @markdown Load the prepared datasets

import os
import json
import pandas as pd
from datasets import Dataset

# Define a function to manually load JSONL files
def load_jsonl_dataset(file_path):
    """Load JSONL file and convert to a datasets.Dataset object"""
    data = []
    with open(file_path, 'r') as f:
        for line in f:
            data.append(json.loads(line))
    return Dataset.from_pandas(pd.DataFrame(data))

# Check if paths exist and load datasets
if os.path.exists(train_path) and os.path.exists(val_path):
    print(f"Loading datasets from {train_path} and {val_path}")
    train_dataset = load_jsonl_dataset(train_path)
    val_dataset = load_jsonl_dataset(val_path)

    print(f"Loaded {len(train_dataset)} training examples")
    print(f"Loaded {len(val_dataset)} validation examples")

    # Show a sample example
    print("\nSample training example:")
    print(f"Prompt: {train_dataset[0]['prompt']}")
    print(f"Completion: {train_dataset[0]['completion']}")
else:
    print(f"Error: Dataset files not found at expected locations:")
    print(f"Training path: {train_path} (exists: {os.path.exists(train_path)})")
    print(f"Validation path: {val_path} (exists: {os.path.exists(val_path)})")

    # Create sample data as fallback
    print("Creating sample datasets as fallback...")
    sample_data = [{
        "prompt": "Category: SCIENCE\nClue: This force keeps planets in orbit around the sun\nAnswer in the form of a question:",
        "completion": "What is gravity?"
    }]
    train_dataset = Dataset.from_pandas(pd.DataFrame(sample_data))
    val_dataset = Dataset.from_pandas(pd.DataFrame(sample_data))

    print(f"Created {len(train_dataset)} sample training examples")
    print(f"Created {len(val_dataset)} sample validation examples")

    print("\nSample training example:")
    print(f"Prompt: {train_dataset[0]['prompt']}")
    print(f"Completion: {train_dataset[0]['completion']}")

Loading datasets from /content/jeopardy-lm/data/jeopardy_train.jsonl and /content/jeopardy-lm/data/jeopardy_val.jsonl
Loaded 36 training examples
Loaded 4 validation examples

Sample training example:
Prompt: Category: MATHEMATICS
Clue: Value of Pi to 2 decimal places
Answer in the form of a question:
Completion: What is 3.14?

In [41]:
# @title Setup Model for Fine-tuning
# @markdown Configure TinyLlama with LoRA adapters

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType

# Model parameters
base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
max_length = 256

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(base_model)
tokenizer.pad_token = tokenizer.eos_token

# Check if GPU is available, adjust settings accordingly
if torch.cuda.is_available():
    print("Loading model with 8-bit quantization on GPU...")
    load_in_8bit = True
    device_map = "auto"
else:
    print("GPU not available. Loading smaller model configuration...")
    # If no GPU, use CPU with less memory
    load_in_8bit = False
    device_map = None

# Load base model with appropriate settings
try:
    model = AutoModelForCausalLM.from_pretrained(
        base_model,
        load_in_8bit=load_in_8bit,
        device_map=device_map,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    )
except Exception as e:
    print(f"Error loading model with 8-bit quantization: {e}")
    print("Falling back to standard loading...")
    model = AutoModelForCausalLM.from_pretrained(
        base_model,
        torch_dtype=torch.float32,
    )

# Prepare for PEFT fine-tuning (only if loaded with quantization)
if load_in_8bit:
    model = prepare_model_for_kbit_training(model)

# Configure LoRA
lora_config = LoraConfig(
    r=16,               # Rank of the update matrices
    lora_alpha=32,      # Parameter for scaling
    lora_dropout=0.05,  # Dropout probability
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    # Target attention modules for TinyLlama
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
)

# Get PEFT model
model = get_peft_model(model, lora_config)

# Print trainable parameters info
def print_trainable_parameters(model):
    trainable_params = 0
    all_params = 0
    for _, param in model.named_parameters():
        all_params += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f"trainable params: {trainable_params:,d} || "
        f"all params: {all_params:,d} || "
        f"trainable%: {100 * trainable_params / all_params:.2f}%"
    )

print_trainable_parameters(model)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Loading model with 8-bit quantization on GPU...

WARNING:accelerate.utils.modeling:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at TinyLlama/TinyLlama-1.1B-Chat-v1.0 and are newly initialized: ['model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

trainable params: 13,877,248 || all params: 1,113,925,632 || trainable%: 1.25%

In [42]:
# @title Fix LoRA Configuration
# @markdown This cell creates a proper LoRA configuration compatible with TinyLlama's architecture

import torch
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType
from transformers import AutoModelForCausalLM

# Load base model (if needed)
if 'model' not in locals() or 'model' not in globals():
    print("Loading model...")
    model = AutoModelForCausalLM.from_pretrained(
        "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
        load_in_8bit=torch.cuda.is_available(),
        device_map="auto" if torch.cuda.is_available() else None,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    )

    if torch.cuda.is_available():
        model = prepare_model_for_kbit_training(model)

# Print model architecture details for debugging
print(f"Model hidden size: {model.config.hidden_size}")
print(f"Number of attention heads: {model.config.num_attention_heads}")
print(f"Number of KV heads: {model.config.num_key_value_heads}")
print(f"Head dimension: {model.config.hidden_size // model.config.num_attention_heads}")

# Create a properly configured LoRA setup
# The key is matching the rank to be compatible with the model's architecture
lora_config = LoraConfig(
    r=8,  # Ensure this is compatible with head dimensions
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    # Target specific modules that we know exist in the model
    # Note: We're only targeting these specific projection matrices for stability
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
)

# Apply LoRA adapter
model = get_peft_model(model, lora_config)

# Print trainable parameters info
def print_trainable_parameters(model):
    trainable_params = 0
    all_params = 0
    for _, param in model.named_parameters():
        all_params += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f"trainable params: {trainable_params:,d} || "
        f"all params: {all_params:,d} || "
        f"trainable%: {100 * trainable_params / all_params:.2f}%"
    )

print("\nTrainable parameters:")
print_trainable_parameters(model)
print("\nLoRA configuration applied successfully")

Model hidden size: 2048
Number of attention heads: 32
Number of KV heads: 4
Head dimension: 64

Trainable parameters:
trainable params: 10,993,664 || all params: 1,111,042,048 || trainable%: 0.99%

LoRA configuration applied successfully

## Import modules and run custom data collator

In [43]:
import torch
from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling
from peft import LoraConfig, get_peft_model

# Create a custom data collator to handle list format inputs
class ListToTensorCollator(DataCollatorForLanguageModeling):
    def __call__(self, features):
        # First convert lists to tensors if needed
        for i, feature in enumerate(features):
            for key in feature:
                if isinstance(feature[key], list):
                    features[i][key] = torch.tensor(feature[key])

        # Then call the parent collator, but exclude token_type_ids
        batch = super().__call__(features)
        if "token_type_ids" in batch:
            del batch["token_type_ids"]  # Remove token_type_ids
        return batch

# Patch to fix ParameterDict error in PEFT
# This needs to be done before loading model
import types
import torch.nn as nn
from torch.nn.modules.container import ParameterDict

# Fix the ParameterDict.__call__ method to avoid error
original_call = ParameterDict.__call__
def safe_call(self, *args, **kwargs):
    raise RuntimeError("For compatibility with PEFT, use self[key] instead of calling ParameterDict directly")

# Only apply patch if we haven't already
if "For compatibility" not in str(ParameterDict.__call__):
    ParameterDict.__call__ = safe_call
    print("Applied ParameterDict patch")

# Get a fresh base model (not the PEFT model)
if hasattr(model, 'get_base_model'):
    print("Getting base model...")
    base_model = model.get_base_model()
else:
    base_model = model

Applied ParameterDict patch
Getting base model...

## Create a data collator to handle list format inputs

In [44]:
# Create a custom data collator to handle list format inputs
class ListToTensorCollator(DataCollatorForLanguageModeling):
    def __call__(self, features):
        # First convert lists to tensors if needed
        for i, feature in enumerate(features):
            for key in feature:
                if isinstance(feature[key], list):
                    features[i][key] = torch.tensor(feature[key])

        # Then call the parent collator, but exclude token_type_ids
        batch = super().__call__(features)

        # Explicitly remove token_type_ids to avoid errors
        if "token_type_ids" in batch:
            del batch["token_type_ids"]

        # Manually pad to max_length
        max_length = max(len(ids) for ids in batch["input_ids"])
        for i in range(len(batch["input_ids"])):
            padding_length = max_length - len(batch["input_ids"][i])
            batch["input_ids"][i] = torch.cat([batch["input_ids"][i], torch.tensor([tokenizer.pad_token_id] * padding_length)])
            batch["attention_mask"][i] = torch.cat([batch["attention_mask"][i], torch.tensor([0] * padding_length)])

        return batch

# Make sure tokenizer has pad token
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id

# Configure LoRA specifically for TinyLlama with grouped attention
lora_config = LoraConfig(
    r=8,  # Set rank to 8 to match TinyLlama
    lora_alpha=16,
    target_modules=["v_proj"],  # Only apply to value projection
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    # Additional options for PEFT compatibility:
    init_lora_weights="gaussian"  # Explicitly set weight initialization
)

# Apply LoRA configuration to base model
print("Applying LoRA configuration...")
model = get_peft_model(base_model, lora_config)
model.print_trainable_parameters()

# Create data collator with our custom wrapper
data_collator = ListToTensorCollator(
    tokenizer=tokenizer,
    mlm=False  # For causal language modeling
)

# Setup training arguments with minimal settings
training_args = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    evaluation_strategy="no",
    logging_steps=10,
    learning_rate=5e-5,
    weight_decay=0.0,
    fp16=False,  # Use full precision
    bf16=False,
    optim="adamw_torch",
    warmup_ratio=0.03,
    save_steps=100,
    save_total_limit=2,
    load_best_model_at_end=False,
    report_to="tensorboard",
    gradient_checkpointing=False,  # Keep disabled
    remove_unused_columns=False,
    max_grad_norm=1.0,
    # Minimize complexity
    dataloader_num_workers=0,
    ddp_find_unused_parameters=False,
)

# Tokenize the datasets
def tokenize_function(examples):
    return tokenizer(examples["prompt"] + examples["completion"], padding="max_length", truncation=True, max_length=max_length)

tokenized_train = train_dataset.map(tokenize_function, batched=True, remove_columns=["prompt", "completion"])
tokenized_val = val_dataset.map(tokenize_function, batched=True, remove_columns=["prompt", "completion"])

Applying LoRA configuration...
trainable params: 10,993,664 || all params: 1,111,042,048 || trainable%: 0.9894912636105739

Map:   0%|          | 0/36 [00:00<?, ? examples/s]

Map:   0%|          | 0/4 [00:00<?, ? examples/s]

### Initialize the trainer

In [ ]:
# Initialize trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val if 'tokenized_val' in locals() else None,
    data_collator=data_collator,
)

# Run training with patched ParameterDict
print("Starting training with ParameterDict patch...")
try:
    # Run training
    trainer.train()

    # Save the fine-tuned model
    model_path = f"{output_dir}/final"
    model.save_pretrained(model_path)
    tokenizer.save_pretrained(model_path)
    print(f"Model fine-tuning complete. Saved to {model_path}")

except Exception as e:
    print(f"Training error: {e}")
    import traceback
    traceback.print_exc()

    # Last resort: simplest working approach
    print("\nFinal fallback - use simplest adapter approach:")

    from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments

    # 1. Load model from scratch
    tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")
    model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")

    # 2. Make sure tokenizer has pad token
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # 3. Freeze all layers except embeddings for simplicity
    for name, param in model.named_parameters():
        if 'embed' in name:  # Only train embedding layer
            param.requires_grad = True
        else:
            param.requires_grad = False

    # 4. Set up minimal training with frozen model
    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=1,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        learning_rate=1e-4,
        weight_decay=0.0,
        fp16=False,
        save_steps=100,
    )

    # 5. Run training with direct Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False),
    )

    trainer.train()
    model.save_pretrained(output_dir + "/final")

In [47]:
# @title Fix for "ParameterDict should not be called" Error with TinyLlama
# @markdown Direct solution for TinyLlama-specific PEFT error

import torch
from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling
from peft import LoraConfig, get_peft_model

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")
model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0", ignore_mismatched_sizes=True)  # Add this argument

# Create a custom data collator to handle list format inputs
class ListToTensorCollator(DataCollatorForLanguageModeling):
    def __call__(self, features):
        # First convert lists to tensors if needed
        for i, feature in enumerate(features):
            for key in feature:
                if isinstance(feature[key], list):
                    features[i][key] = torch.tensor(feature[key])

        # Then call the parent collator, but exclude token_type_ids
        batch = super().__call__(features)
        if "token_type_ids" in batch:
            del batch["token_type_ids"]  # Remove token_type_ids
        return batch

# Patch to fix ParameterDict error in PEFT
# This needs to be done before loading model
import types
import torch.nn as nn
from torch.nn.modules.container import ParameterDict

# Fix the ParameterDict.__call__ method to avoid error
original_call = ParameterDict.__call__
def safe_call(self, *args, **kwargs):
    raise RuntimeError("For compatibility with PEFT, use self[key] instead of calling ParameterDict directly")

# Only apply patch if we haven't already
if "For compatibility" not in str(ParameterDict.__call__):
    ParameterDict.__call__ = safe_call
    print("Applied ParameterDict patch")

# Get a fresh base model (not the PEFT model)
if hasattr(model, 'get_base_model'):
    print("Getting base model...")
    base_model = model.get_base_model()
else:
    base_model = model

Some weights of LlamaForCausalLM were not initialized from the model checkpoint at TinyLlama/TinyLlama-1.1B-Chat-v1.0 and are newly initialized: ['model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at TinyLlama/TinyLlama-1.1B-Chat-v1.0 and are newly initialized because the shapes did not match:
- model.layers.0.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.0.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.1.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.1.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.10.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.10.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.11.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.11.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.12.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.12.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.13.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.13.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.14.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.14.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.15.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.15.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.16.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.16.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.17.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.17.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.18.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.18.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.19.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.19.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.2.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.2.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.20.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.20.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.21.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.21.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.3.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.3.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.4.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.4.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.5.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.5.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.6.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.6.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.7.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.7.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.8.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.8.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.9.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.9.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Applied ParameterDict patch

In [48]:
# Ensure tokenizer has padding token
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Freeze most parameters and only train a subset
trainable_layers = ["lm_head"]  # Only train the output layer

# Freeze all parameters except those in trainable_layers
for name, param in model.named_parameters():
    param.requires_grad = False
    for layer_name in trainable_layers:
        if layer_name in name:
            param.requires_grad = True
            print(f"Training: {name}")

# Create data collator for language modeling
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False  # For causal language modeling
)

# Training arguments
training_args = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=1,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    evaluation_strategy="no",
    learning_rate=1e-4,
    weight_decay=0.0,
    fp16=torch.cuda.is_available(),
    save_strategy="epoch",
    save_total_limit=1,
)

# Initialize trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    data_collator=data_collator,
)

# Train model
print("Starting training...")
trainer.train()

# Save the fine-tuned model
model.save_pretrained(f"{output_dir}/final")
tokenizer.save_pretrained(f"{output_dir}/final")
print(f"Model saved to {output_dir}/final")

Training: lm_head.weight
Starting training...

/usr/local/lib/python3.11/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
You're using a LlamaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

Model saved to /content/jeopardy-lm/final

In [52]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments, DataCollatorForLanguageModeling

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")
model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0", ignore_mismatched_sizes=True)

# Ensure tokenizer has padding token
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Freeze most parameters and only train a subset
trainable_layers = ["lm_head"]  # Only train the output layer

# Freeze all parameters except those in trainable_layers
for name, param in model.named_parameters():
    param.requires_grad = False
    for layer_name in trainable_layers:
        if layer_name in name:
            param.requires_grad = True
            print(f"Training: {name}")

# Create data collator for language modeling
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False  # For causal language modeling
)

# Training arguments
training_args = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=1,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    evaluation_strategy="no",
    learning_rate=1e-4,
    weight_decay=0.0,
    fp16=torch.cuda.is_available(),
    save_strategy="epoch",
    save_total_limit=1,
)

# Initialize trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    data_collator=data_collator,
)

# Train model
print("Starting training...")
trainer.train()

# Save the fine-tuned model
model.save_pretrained(f"{output_dir}/final")
tokenizer.save_pretrained(f"{output_dir}/final")
print(f"Model saved to {output_dir}/final")

Some weights of LlamaForCausalLM were not initialized from the model checkpoint at TinyLlama/TinyLlama-1.1B-Chat-v1.0 and are newly initialized: ['model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at TinyLlama/TinyLlama-1.1B-Chat-v1.0 and are newly initialized because the shapes did not match:
- model.layers.0.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.0.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.1.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.1.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.10.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.10.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.11.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.11.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.12.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.12.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.13.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.13.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.14.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.14.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.15.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.15.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.16.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.16.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.17.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.17.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.18.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.18.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.19.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.19.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.2.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.2.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.20.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.20.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.21.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.21.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.3.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.3.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.4.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.4.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.5.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.5.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.6.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.6.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.7.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.7.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.8.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.8.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.9.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.9.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Training: lm_head.weight
Starting training...

/usr/local/lib/python3.11/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
You're using a LlamaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

Model saved to /content/jeopardy-lm/final

In [54]:
# @title Final Lightweight Training Approach
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments, DataCollatorForLanguageModeling

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")
model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0", ignore_mismatched_sizes=True)

# Ensure tokenizer has padding token
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Freeze most parameters and only train a subset
trainable_layers = ["lm_head"]  # Only train the output layer

# Freeze all parameters except those in trainable_layers
for name, param in model.named_parameters():
    param.requires_grad = False
    for layer_name in trainable_layers:
        if layer_name in name:
            param.requires_grad = True
            print(f"Training: {name}")

# Create data collator for language modeling
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False  # For causal language modeling
)

# Training arguments
training_args = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=1,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    evaluation_strategy="no",
    learning_rate=1e-4,
    weight_decay=0.0,
    fp16=torch.cuda.is_available(),
    save_strategy="epoch",
    save_total_limit=1,
)

# Initialize trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    data_collator=data_collator,
)

# Train model
print("Starting training...")
trainer.train()

# Save the fine-tuned model
model.save_pretrained(f"{output_dir}/final")
tokenizer.save_pretrained(f"{output_dir}/final")
print(f"Model saved to {output_dir}/final")

Some weights of LlamaForCausalLM were not initialized from the model checkpoint at TinyLlama/TinyLlama-1.1B-Chat-v1.0 and are newly initialized: ['model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at TinyLlama/TinyLlama-1.1B-Chat-v1.0 and are newly initialized because the shapes did not match:
- model.layers.0.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.0.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.1.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.1.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.10.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.10.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.11.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.11.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.12.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.12.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.13.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.13.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.14.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.14.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.15.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.15.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.16.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.16.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.17.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.17.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.18.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.18.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.19.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.19.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.2.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.2.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.20.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.20.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.21.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.21.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.3.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.3.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.4.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.4.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.5.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.5.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.6.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.6.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.7.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.7.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.8.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.8.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.9.self_attn.k_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
- model.layers.9.self_attn.v_proj.weight: found shape torch.Size([256, 2048]) in the checkpoint and torch.Size([2048, 2048]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Training: lm_head.weight

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <cell line: 0>:46                                                                             │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/transformers/trainer.py:511 in __init__                  │
│                                                                                                  │
│    508 │   │   self.tokenizer = tokenizer                                                        │
│    509 │   │                                                                                     │
│    510 │   │   if self.place_model_on_device and not getattr(model, "is_loaded_in_8bit", False)  │
│ ❱  511 │   │   │   self._move_model_to_device(model, args.device)                                │
│    512 │   │                                                                                     │
│    513 │   │   # Force n_gpu to 1 to avoid DataParallel as MP will manage the GPUs               │
│    514 │   │   if self.is_model_parallel:                                                        │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/transformers/trainer.py:754 in _move_model_to_device     │
│                                                                                                  │
│    751 │   │   self.callback_handler.remove_callback(callback)                                   │
│    752 │                                                                                         │
│    753 │   def _move_model_to_device(self, model, device):                                       │
│ ❱  754 │   │   model = model.to(device)                                                          │
│    755 │   │   # Moving a model to an XLA device disconnects the tied weights, so we have to re  │
│    756 │   │   if self.args.parallel_mode == ParallelMode.TPU and hasattr(model, "tie_weights")  │
│    757 │   │   │   model.tie_weights()                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/transformers/modeling_utils.py:1902 in to                │
│                                                                                                  │
│   1899 │   │   │   │   " model has already been set to the correct devices and casted to the co  │
│   1900 │   │   │   )                                                                             │
│   1901 │   │   else:                                                                             │
│ ❱ 1902 │   │   │   return super().to(*args, **kwargs)                                            │
│   1903 │                                                                                         │
│   1904 │   def half(self, *args):                                                                │
│   1905 │   │   # Checks if the model has been loaded in 8-bit                                    │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1145 in to                    │
│                                                                                                  │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│   1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│   1144 │   │                                                                                     │
│ ❱ 1145 │   │   return self._apply(convert)                                                       │
│   1146 │                                                                                         │
│   1147 │   def register_full_backward_pre_hook(                                                  │
│   1148 │   │   self,                                                                             │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:797 in _apply                 │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:797 in _apply                 │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:797 in _apply                 │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:797 in _apply                 │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:797 in _apply                 │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:820 in _apply                 │
│                                                                                                  │
│    817 │   │   │   # track autograd history of `param_applied`, so we have to use                │
│    818 │   │   │   # `with torch.no_grad():`                                                     │
│    819 │   │   │   with torch.no_grad():                                                         │
│ ❱  820 │   │   │   │   param_applied = fn(param)                                                 │
│    821 │   │   │   should_use_set_data = compute_should_use_set_data(param, param_applied)       │
│    822 │   │   │   if should_use_set_data:                                                       │
│    823 │   │   │   │   param.data = param_applied                                                │
│                                                                                                  │
│ /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1143 in convert               │
│                                                                                                  │
│   1140 │   │   │   if convert_to_format is not None and t.dim() in (4, 5):                       │
│   1141 │   │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() els  │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│ ❱ 1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│   1144 │   │                                                                                     │
│   1145 │   │   return self._apply(convert)                                                       │
│   1146                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 14.74 GiB total capacity; 14.14 GiB
already allocated; 10.12 MiB free; 14.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated
memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and
PYTORCH_CUDA_ALLOC_CONF

In [55]:
# @title Create Demo Interface
# @markdown Create a simple demo interface in Colab

from IPython.display import display, HTML
import ipywidgets as widgets

# Check if we have a model loaded
try:
    model
except NameError:
    print("ERROR: Model not found. Please run the training and evaluation cells first.")
    model = None

if model is not None:
    # Create input widgets
    category_input = widgets.Text(
        value='',
        placeholder='Enter category',
        description='Category:',
        disabled=False
    )

    clue_input = widgets.Textarea(
        value='',
        placeholder='Enter clue',
        description='Clue:',
        disabled=False
    )

    submit_button = widgets.Button(
        description='Get Answer',
        disabled=False,
        button_style='primary',
        tooltip='Click to get the answer',
        icon='check'
    )

    output_area = widgets.Output()

    # Define submit function
    def on_submit_clicked(b):
        with output_area:
            output_area.clear_output()

            category = category_input.value
            clue = clue_input.value

            if not category or not clue:
                print("Please enter both category and clue.")
                return

            print("Generating answer...")

            # Format the prompt
            prompt = f"Category: {category}\nClue: {clue}\nAnswer in the form of a question:"

            try:
                # Tokenize and generate
                inputs = tokenizer(prompt, return_tensors="pt")
                if torch.cuda.is_available():
                    inputs = inputs.to("cuda")

                outputs = model.generate(
                    inputs.input_ids,
                    max_new_tokens=50,
                    temperature=0.7,
                    top_p=0.9,
                    do_sample=True
                )

                # Decode and extract answer
                response = tokenizer.decode(outputs[0], skip_special_tokens=True)
                answer = response.replace(prompt, "").strip()

                print(f"\nAnswer: {answer}")
            except Exception as e:
                print(f"Error generating answer: {e}")

    # Connect button to function
    submit_button.on_click(on_submit_clicked)

    # Display widgets
    print("Jeopardy Question Answering Demo")
    display(category_input)
    display(clue_input)
    display(submit_button)
    display(output_area)

Jeopardy Question Answering Demo

Text(value='', description='Category:', placeholder='Enter category')

Textarea(value='', description='Clue:', placeholder='Enter clue')

Button(button_style='primary', description='Get Answer', icon='check', style=ButtonStyle(), tooltip='Click to …

Output()

In [ ]:
# @title Download Fine-tuned Model (Optional)
# @markdown Download the fine-tuned model to your local machine

from google.colab import files
import shutil

try:
    # Check if model_path exists
    if 'model_path' not in globals() or not os.path.exists(model_path):
        print("Model not found. Please complete the training process first.")
    else:
        # Compress the model directory
        print(f"Compressing model from {model_path}...")
        !zip -r {output_dir}/jeopardy_model.zip {model_path}

        # Download the compressed file
        print("Downloading model zip file...")
        files.download(f"{output_dir}/jeopardy_model.zip")

        print("Model downloaded. To use this model locally:")
        print("1. Extract the ZIP file")
        print("2. Load it with PeftModel.from_pretrained()")
        print("3. Use the provided API server code in the next cell")
except Exception as e:
    print(f"Error downloading model: {e}")
    print("If you're not in Colab, you can manually copy the model files from the output directory.")

## API Server Code (For Local Use)

This code can be used to create a simple API server for the fine-tuned model when running locally. Save this to a file named `api_server.py`:

```python
# Flask API Server Implementation for Local Use
# Save this to a file named "api_server.py" on your local machine

from flask import Flask, request, jsonify
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

app = Flask(__name__)

# Update these paths to match your local setup
base_model_path = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "./jeopardy_model"  # Path to extracted model adapters

# Load the tokenizer and model
print("Loading tokenizer and model...")
tokenizer = AutoTokenizer.from_pretrained(base_model_path)

# Check for GPU and load model accordingly
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

base_model = AutoModelForCausalLM.from_pretrained(
    base_model_path,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32,
    device_map="auto" if device == "cuda" else None,
)

# Load fine-tuned model
model = PeftModel.from_pretrained(base_model, adapter_path)
model.eval()  # Set to evaluation mode

print("Model loaded successfully")

@app.route('/predict', methods=['POST'])
def predict():
    # Get JSON data from request
    data = request.json
    if not data or 'category' not in data or 'clue' not in data:
        return jsonify({'error': 'Please provide both category and clue fields'}), 400
    
    category = data['category']
    clue = data['clue']
    
    # Format the prompt
    prompt = f"Category: {category}\nClue: {clue}\nAnswer in the form of a question:"
    
    # Generate answer
    try:
        inputs = tokenizer(prompt, return_tensors="pt")
        if device == "cuda":
            inputs = inputs.to("cuda")
        
        with torch.no_grad():
            outputs = model.generate(
                inputs.input_ids,
                max_new_tokens=50,
                temperature=0.7,
                top_p=0.9,
                do_sample=True
            )
        
        # Decode the output
        response = tokenizer.decode(outputs[0], skip_special_tokens=True)
        answer = response.replace(prompt, "").strip()
        
        return jsonify({
            'category': category,
            'clue': clue,
            'answer': answer
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/', methods=['GET'])
def home():
    return """
    <h1>Jeopardy API Server</h1>
    <p>Make a POST request to /predict with JSON data containing 'category' and 'clue'.</p>
    <p>Example:</p>
    <pre>{
  "category": "HISTORY",
  "clue": "This document, signed in 1776, announced that the 13 American colonies were no longer part of Great Britain"
}</pre>
    """

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=False)
```

### Usage Instructions:

1. Install the required packages: `pip install flask torch transformers peft`
2. Update the `adapter_path` to point to your extracted model
3. Run the server: `python api_server.py`
4. Access the API at `http://localhost:5000/predict`

### Example cURL request:

```bash
curl -X POST http://localhost:5000/predict \
  -H "Content-Type: application/json" \
  -d '{"category":"SCIENCE", "clue":"This force keeps planets in orbit around the sun"}'
```

## Final Notes

This notebook demonstrates a complete pipeline for fine-tuning TinyLlama-1.1B on Jeopardy questions using LoRA. Here's a summary of what we've accomplished:

1. **Data Preparation**: Downloaded and processed Jeopardy questions into an instruction tuning format
2. **Model Fine-tuning**: Used PEFT/LoRA to efficiently fine-tune TinyLlama without requiring extensive computational resources
3. **Evaluation**: Tested the model's performance on Jeopardy questions
4. **Interactive Demo**: Created a simple interface to interact with the model
5. **Deployment**: Provided code for deploying the model as an API server

### Improving the Model

To improve the model's performance, you could try:

- Using a larger base model (if you have more computational resources)
- Fine-tuning for more epochs
- Adjusting hyperparameters (learning rate, batch size, etc.)
- Enhancing the data preprocessing (better handling of question format, more data)
- Using a more sophisticated evaluation metric

### Next Steps

- Try creating a more comprehensive interactive application
- Experiment with different prompt formats
- Apply the same technique to other trivia or question-answering datasets
- Deploy the model to a production environment

Happy fine-tuning!